# Generated by Django 5.0 on 2023-12-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_remove_cart_id_alter_cart_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='uuid',
            new_name='id',
        ),
    ]
